name: python app model test and deploy

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: flake8 run
        run: |
          flake8 .
      - name: run pytest
        run: |
          pytest ./test.py && pytest ./test_api.py
